### ISSUE TITLE
Rework the course overview functionality

### ISSUE THREAD

**Issue by benjaminjost** [prodingerd/software-technology#19]
- Implement a central solution to store and fetch course data from/to for the recycler view.
  (Currently there is only a temporary list in the CustomCourseAdaper file).
- Maybe also take a look on how to update the recycler view dynamically
- Add a count of course cards in the list view adapter.

**Comment by prodingerd** [comment]
This was implicitly done through other issues already, closing this in favor of more specific updates to the overview in the upcoming sprint.
